services:
  db:
    image: postgres:16
    container_name: onboardpro_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: ThisIsAStrongPassword567!
      POSTGRES_DB: onboardpro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d onboardpro"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata: